import "./globals.css";


import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/header";
import Footers from "@/components/footer";
import TopBar from "@/components/top-bar";
import { Toaster } from "@/components/ui/sonner";
import FramerMotionProvider from "@/contexts/framer-motion";
import ReactQueryProvider from "@/contexts/react-query-provider";
import { getContactSettings } from "@/lib/contact-settings";
import { getFunds } from "@/services/fundService";

const inter = Inter({
  variable: "--font-inter",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ceybank",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  const [contactSettings, funds] = await Promise.all([
    getContactSettings(),
    getFunds().catch(() => []),
  ]);
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased bg-primary`}>
        <ReactQueryProvider>
          <div className="space-y-2.5">
            <TopBar contactSettings={contactSettings} />
            <Header funds={funds} />
          </div>
          <FramerMotionProvider>
            {children}
          </FramerMotionProvider>
          <Footers contactSettings={contactSettings} funds={funds} />
          <Toaster theme="light" />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
